services:
  curl:
    image: curlimages/curl
    depends_on:
      lambda:
        condition: service_healthy
    command:
      - -s
      - -d
      - ${LAMBDA_INPUT:-{}}
      - http://lambda:8080/2015-03-31/functions/function/invocations
    volumes:
      - ./events:/events:ro
  lambda:
    build: .
    healthcheck:
      test:
        - CMD
        - curl
        - -I
        - http://localhost:8080
      interval: 1s
      timeout: 1s
      retries: 30
    environment:
      AWS_LAMBDA_FUNCTION_MEMORY_SIZE: 128
      AWS_LAMBDA_FUNCTION_TIMEOUT: 3
      AWS_LAMBDA_LOG_FORMAT: JSON
